services:
  helios:
    container_name: helios
    init: true
    build: ./helios

    environment:
      - DATABASE_URL=postgres://helios:helios@postgres/helios
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=helios
      - PGPASSWORD=helios
      - AUTH_ENABLED_SYSTEMS=ldap
      - AUTH_DEFAULT_SYSTEM=ldap
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: helios
      POSTGRES_PASSWORD: helios
      POSTGRES_DB: helios
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helios"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
